spring.application.name=Pair of Players App
server.port=8080


app.files.players=files/players.csv
app.files.matches=files/matches.csv
app.files.teams=files/teams.csv
app.files.records=files/records.csv


spring.datasource.url=jdbc:mysql://localhost:3306/pair_players_db
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
